name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, xdebug

      - name: Install
        run: make install

      - name: Run Lint
        run: make lint

      - name: Prepare CodeClimate Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}

      - name: Run Tests with Coverage
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
        env:
          XDEBUG_MODE: coverage

      - name: Upload Coverage to CodeClimate
        run: ./cc-test-reporter after-build --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
